---
MethodLength:
  Max: 200

LineLength:
  Max: 160

PerceivedComplexity:
  Enabled: false

CyclomaticComplexity:
  Enabled: false

ClassLength:
  Enabled: false

Documentation:
  Enabled: false

IfUnlessModifier:
  Enabled: false

