---
Metrics/MethodLength:
  Max: 200

Metrics/LineLength:
  Max: 160

Metrics/PerceivedComplexity:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Style/IndentationWidth:
  Width: 4
